notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
branches:
  only:
    - all
    - master
install: true
jobs:
  include:
    # maven
    - stage: maven
      name: "Java 8"
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR
        - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
        - ./mvnw
    # gradle
    - stage: gradle
      name: "Java 8"
      jdk: openjdk8
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
cache:
  directories:
    - ~/.gradle
    - ~/.m2
