env:
  global:
    - TERM=dumb
dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
node_js: lts/*
python: 3
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - python3-pip
install: true
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: default tasks
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk11
      name: default tasks (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk8
      name: integration tests
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/api/mvc | jq '.'
        - http :8080/api/mvc body="hello mvc" | jq '.'
        - http :8080/api/mvc/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/api/mvc | jq '.'
        - http :8080/api/mvc body="hello mvc" | jq '.'
        - http :8080/api/mvc/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: gradle updates
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk11
      name: gradle updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk8
      name: maven default tasks
      script: cd $TRAVIS_BUILD_DIR && ./mvnw
    - stage: test
      jdk: openjdk11
      name: maven default tasks (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw
    - stage: test
      jdk: openjdk8
      name: maven integration tests
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw package -DskiTests
        - java -jar $TRAVIS_BUILD_DIR/target/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/api/mvc | jq '.'
        - http :8080/api/mvc body="hello mvc" | jq '.'
        - http :8080/api/mvc/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: maven integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw package -DskiTests
        - java -jar $TRAVIS_BUILD_DIR/target/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/api/mvc | jq '.'
        - http :8080/api/mvc body="hello mvc" | jq '.'
        - http :8080/api/mvc/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: maven updates
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
    - stage: test
      jdk: openjdk11
      name: maven updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
