notifications:
  email: false
git:
  quiet: true
  depth: 1

language: java
jdk: openjdk8
node_js: lts/*
python: 3

service:
  - docker

addons:
  apt:
    update: true
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools

install: true
before_install:
  - docker-compose -v
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432

jobs:
  include:

    - stage: test
      jdk: openjdk8
      name: Run tests (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test

    - stage: test
      jdk: openjdk11
      name: Run tests (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test

    - stage: test
      jdk: openjdk8
      name: Build uberJar profile and run integration tests (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew clean quarkusBuild --uber-jar
        - java -jar $TRAVIS_BUILD_DIR/build/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        - http :8080/metrics accept:application/json
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - stop_any 80 8080

    - stage: test
      jdk: openjdk11
      name: Build uberJar profile and run integration tests (openjdk11)
      script:
      - cd $TRAVIS_BUILD_DIR && ./gradlew clean quarkusBuild --uber-jar
      - java -jar $TRAVIS_BUILD_DIR/build/*-runner.jar &
      - wait_for 8080
      - http :8080
      - http :8080/health
      - http :8080/openapi
      - http :8080/metrics accept:application/json
      - http :8080/api/v1/hello
      - http :8080/api/v1/hello/%20
      - http :8080/api/v1/hello/maksimko
      - stop_any 80 8080

    - stage: test
      jdk: openjdk8
      name: Build quarkus thin jar and run integration tests (openjdk8)
      script:
      - cd $TRAVIS_BUILD_DIR && ./gradlew clean quarkusBuild
      - java -cp $TRAVIS_BUILD_DIR/build/lib -jar $TRAVIS_BUILD_DIR/build/*-runner.jar &
      - wait_for 8080
      - http :8080
      - http :8080/health
      - http :8080/openapi
      - http :8080/metrics accept:application/json
      - http :8080/api/v1/hello
      - http :8080/api/v1/hello/%20
      - http :8080/api/v1/hello/maksimko
      - stop_any 80 8080

    - stage: test
      jdk: openjdk11
      name: Build quarkus thin jar and run integration tests (openjdk11)
      script:
      - cd $TRAVIS_BUILD_DIR && ./gradlew clean quarkusBuild
      - java -cp $TRAVIS_BUILD_DIR/build/lib -jar $TRAVIS_BUILD_DIR/build/*-runner.jar &
      - wait_for 8080
      - http :8080
      - http :8080/health
      - http :8080/openapi
      - http :8080/metrics accept:application/json
      - http :8080/api/v1/hello
      - http :8080/api/v1/hello/%20
      - http :8080/api/v1/hello/maksimko
      - stop_any 80 8080

    - stage: test
      jdk: openjdk8
      name: Test app with docker-compose plugin (openjdk8)
      script:
      - cd $TRAVIS_BUILD_DIR && ./gradlew clean composeUp
      - wait_for 8080
      - http :8080
      - http :8080/health
      - http :8080/openapi
      - http :8080/metrics accept:application/json
      - http :8080/api/v1/hello
      - http :8080/api/v1/hello/%20
      - http :8080/api/v1/hello/maksimko
      - cd $TRAVIS_BUILD_DIR && ./gradlew composeDown

    - stage: test
      jdk: openjdk8
      name: Test Dockerfile.jvm (openjdk8)
      script:
      - cd $TRAVIS_BUILD_DIR && ./gradlew clean quarkusBuild
      - docker build -f src/main/docker/Dockerfile.jvm -t quarkus/quarkus-example-jvm .
      - docker run -i --rm --name jvm-app -p 8080:8080 quarkus/quarkus-example-jvm &
      - wait_for 8080
      - sleep 3s
      - wait_for 8080
      - http :8080
      - http :8080/health
      - http :8080/openapi
      - http :8080/metrics accept:application/json
      - http :8080/api/v1/hello
      - http :8080/api/v1/hello/%20
      - http :8080/api/v1/hello/maksimko
      - docker rm -f -v jvm-app

    - stage: test
      jdk: openjdk8
      name: Test Dockerfile.native (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew clean buildNative --docker-build=true
        - docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-example-native .
        - docker run -i --rm --name native-app -p 8080:8080 quarkus/quarkus-example-native &
        - wait_for 8080
        - sleep 3s
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        - http :8080/metrics accept:application/json
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - docker rm -f -v native-app

    - stage: test
      jdk: openjdk8
      name: Run versions display updates command (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release

    - stage: test
      jdk: openjdk11
      name: Run versions display updates command (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release

cache:
  directories:
    - ~/.docker
    - ~/.gradle
  packages: true
  pip: true
