notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
branches:
  only:
    - all
    - master
    - scala
    - spring
    - spring-boot
    - spring-scala
install: true
jobs:
  include:
    # maven
    - stage: maven
      name: "Maven Java 8 Build"
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR
        - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
        - ./mvnw
    - stage: maven
      name: "Maven Java 11 Build"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw
    - stage: maven
      name: "Maven Java 11 Updates"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
    # gradle
    - stage: gradle
      name: "Gradle Java 8 Build"
      jdk: openjdk8
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: gradle
      name: "Gradle Java 11 Build"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: gradle
      name: "Gradle Java 11 Updates"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
    - ~/.m2
