dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
python: 3
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - docker-ce
      - python3-pip
install: true
before_install:
  # leiningen
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use leiningen 2.9.1
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  #
  - which pip  || echo 'which pip  command failed.'
  - which pip3 || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - which pip  || echo 'which pip  command failed.'
  - which pip3 || echo 'which pip3 command failed.'
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  - docker-compose -v
  #- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  #- docker-compose -v
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5672 5432 27017 >/dev/null
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: maven build
      script:
        - cd $TRAVIS_BUILD_DIR && lein test
        - cd $TRAVIS_BUILD_DIR && lein uberjar
        - java -jar $TRAVIS_BUILD_DIR/target/uberjar/*-standalone.jar
    - stage: test
      jdk: openjdk11
      name: maven build (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && lein test
        - cd $TRAVIS_BUILD_DIR && lein uberjar
        - java -jar $TRAVIS_BUILD_DIR/target/uberjar/*-standalone.jar
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
