notifications:
  email: false
git:
  quiet: true
  depth: false
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
python: 3.7
addons:
  apt:
    update: true
    packages:
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - python3-pip
install: true
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
  - |
    if [ ! -f ~/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ~/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ~/.local/daggerok/bash-functions/master/main.bash ;
    fi
  - source ~/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 8080 5672 5432 27017 >/dev/null
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: Maven build (openjdk8)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-maven.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U
    - stage: test
      jdk: openjdk8
      name: Maven updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
    - stage: test
      jdk: openjdk8
      name: Gradle build (openjdk8)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk8
      name: Gradle updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk11
      name: Maven build (openjdk11)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-maven.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U
    - stage: test
      jdk: openjdk11
      name: Maven updates (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates -U >/dev/null
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-parent-updates versions:display-dependency-updates versions:display-property-updates
    - stage: test
      jdk: openjdk11
      name: Gradle build (openjdk11)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk11
      name: Gradle updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
cache:
  pip: true
  packages: true
  directories:
    - ~/.local/daggerok
    - ~/.gradle
    - ~/.m2
