notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: true
addons:
  apt:
    update: true
    packages:
      - zip
      - unzip
      - curl
      - bash
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle 5.5-rc-4
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: Maven Java 8 Build (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR
        - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
        - ./mvnw
        - java -jar target/*-SNAPSHOT.jar
    - stage: test
      jdk: openjdk8
      name: Maven Java 8 Updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && mvn -N io.takari:maven:wrapper -Dmaven=3.6.1 && ./mvnw versions:display-property-updates
    - stage: test
      jdk: openjdk8
      name: Gradle Java 8 Build (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR
        - gradle :wrapper
        - ./gradlew
        - java -jar build/libs/*-SNAPSHOT.jar
    - stage: test
      jdk: openjdk8
      name: Gradle Java 8 Updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && gradle :wrapper && ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk11
      name: Maven Java 11 Build (openjdk11)
      script: cd $TRAVIS_BUILD_DIR ; mvn -N io.takari:maven:wrapper -Dmaven=3.6.1 ; ./mvnw ; java -jar target/*-SNAPSHOT.jar
    - stage: test
      jdk: openjdk11
      name: Maven Java 11 Updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR ; mvn -N io.takari:maven:wrapper -Dmaven=3.6.1 ; ./mvnw versions:display-property-updates
    - stage: test
      jdk: openjdk11
      name: Gradle Java 11 Build (openjdk11)
      script: cd $TRAVIS_BUILD_DIR ; gradle :wrapper ; ./gradlew ; java -jar build/libs/*-SNAPSHOT.jar
    - stage: test
      jdk: openjdk11
      name: Gradle Java 11 Updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR ; gradle :wrapper ; ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
