dist: xenial

notifications:
  email: false
git:
  quiet: true
  depth: 1

language: java
jdk: openjdk8
node_js: lts/*
python: 3

service:
  - docker
  - xvfb

addons:
  apt:
    update: true
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - libxml2-utils
      - unzip
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable

install: true
before_install:
  - docker-compose -v
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432

stages:
  - test
  - maintain

jobs:
  include:

    - stage: test
      jdk: openjdk8
      name: Run gradle tests (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test

    - stage: test
      jdk: openjdk11
      name: Run gradle tests (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test

    - stage: test
      jdk: openjdk8
      name: Run maven tests (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw clean test -U

    - stage: test
      jdk: openjdk11
      name: Run maven tests (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw clean test -U

    - stage: test
      jdk: openjdk8
      name: Build uberJar profile and run integration tests (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -DskipTests package -PuberJar -U
        - java -jar target/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - stop_any 80 8080

    - stage: test
      jdk: openjdk11
      name: Build uberJar profile and run integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -DskipTests package -PuberJar -U
        - java -jar target/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - stop_any 80 8080

    - stage: test
      jdk: openjdk8
      name: Build quarkus uberJar and run integration tests (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw compile jar:jar quarkus:build -U
        - java -jar target/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - stop_any 80 8080

    - stage: test
      jdk: openjdk11
      name: Build quarkus uberJar and run integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw compile jar:jar quarkus:build -U
        - java -jar target/*-runner.jar &
        - wait_for 8080
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - stop_any 80 8080

    - stage: test
      jdk: openjdk8
      name: Test app with maven docker-compose plugin (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -P docker compile jar:jar quarkus:build docker-compose:up -U
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        - cd $TRAVIS_BUILD_DIR && ./mvnw -P docker docker-compose:down

    - stage: test
      jdk: openjdk8
      name: Test Dockerfile.jvm (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw clean compile jar:jar quarkus:build -U
        - docker build -f src/main/docker/Dockerfile.jvm -t quarkus/quarkus-example-jvm .
        - docker run -i --rm --name jvm-app -p 8080:8080 quarkus/quarkus-example-jvm &
        - wait_for 8080
        - sleep 3s
        #
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        #
        - docker rm -f -v jvm-app

    - stage: test
      jdk: openjdk8
      name: Test Dockerfile.native (openjdk8)
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw package -Pnative -Dnative-image.docker-build=true -U
        - docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-example-native .
        - docker run -i --rm --name native-app -p 8080:8080 quarkus/quarkus-example-native &
        - wait_for 8080
        - sleep 3s
        #
        - http :8080
        - http :8080/health
        - http :8080/openapi
        #- http :8080/metrics
        - http :8080/swagger-ui
        #- http :8080/swagger-ui/
        - http :8080/api/v1/hello
        - http :8080/api/v1/hello/%20
        - http :8080/api/v1/hello/maksimko
        #
        - docker rm -f -v native-app

    - stage: maintain
      jdk: openjdk8
      name: Run mvn versions:display-property-updates command (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
    - stage: maintain
      jdk: openjdk11
      name: Run mvn versions:display-property-updates command (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

cache:
  directories:
    - ~/.m2
    - ~/.gradle
    - ~/.docker
  packages: true
  pip: true
