dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
python: 3
branches:
  only:
    - all
    - scala
    - maven
    - master
    - spring
    - gradle
    - maven-java
    - spring-boot
    - quarkus-scala
    - gradle-kotlin
    - quarkus-gradle
    - quarkus-maven
    - spring-fu-jafu
    - spring-boot-all
    - spring-boot-scala
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - docker-ce
      - python3-pip
install: true
before_install:
  ## gradle
  #- curl -s "https://get.sdkman.io" | bash
  #- source "$HOME/.sdkman/bin/sdkman-init.sh"
  #- sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  #- sdk use gradle 5.5-rc-4
  #- source "$HOME/.sdkman/bin/sdkman-init.sh"
  ##
  - which pip  || echo 'which pip  command failed.'
  - which pip3 || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - which pip  || echo 'which pip  command failed.'
  - which pip3 || echo 'which pip3 command failed.'
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  - docker-compose -v
  #- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  #- docker-compose -v
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5672 5432 27017 >/dev/null
jobs:
  include:
    # openjdk8
    - stage: test
      jdk: openjdk8
      name: Maven build (openjdk8)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-maven.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U
    - stage: test
      jdk: openjdk8
      name: Maven updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
    - stage: test
      jdk: openjdk8
      name: Gradle build (openjdk8)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk8
      name: Gradle updates (openjdk8)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
    # openjdk11
    - stage: test
      jdk: openjdk11
      name: Maven build (openjdk11)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-maven.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -U
    - stage: test
      jdk: openjdk11
      name: Maven updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U
    - stage: test
      jdk: openjdk11
      name: Gradle build (openjdk11)
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/src/main/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk11
      name: Gradle updates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
