####
# ./gradlew buildNative --docker-build=true
# docker build -f src/main/docker/Dockerfile.native -t quarkus/app .
# docker run -i --rm -p 8080:8080 quarkus/app
###

FROM registry.access.redhat.com/ubi8/ubi-minimal
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
EXPOSE 8080
WORKDIR /work/
COPY build/*-runner /work/application
RUN chmod 775 /work
