####
# gradle build
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/app .
# docker run -i --rm -p 8080:8080 quarkus/app
###

FROM fabric8/java-jboss-openjdk8-jdk
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0"
ENTRYPOINT ["/deployments/run-java.sh"]
HEALTHCHECK CMD curl -f http://127.0.0.1:8080/health || exit 1
COPY build/lib/*        /deployments/lib/
COPY build/*-runner.jar /deployments/app.jar
